[admiral]
items = ["left", "padding", "workspaces", "right", "spotify", "padding", "network", "padding", "volume", "padding", "battery", "padding", "clock", "padding"]

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[padding]
path = "echo '   '"
static = true

[spotify]
path = "reloader.rb 2 sp_current.rb | roller -t 40 -b '%{A4:sp prev:}%{A5:sp next:}%{A:sp play:}%{F#645263}%{F-} ' -a '%{A}%{A}%{A}' -s ' --- '"

[title]
path = "xtitle -s | roller -t 50 -i 150"

[launcher]
path = "launcher.sh"
static = true

[clock]
path = "date +%H:%M"
reload = 1

[battery]
path = "battery.sh"
reload = 3

[network]
path = "network_name.sh"
reload = 5

[volume]
path = "volume.sh"
reload = 0.01

[hostname]
path = "hostname.sh"
static = true

[workspaces]
path = "workspaces.sh"
