#!/usr/bin/fish

sxhkd &

bspc config border_width        3
bspc config window_gap          20
bspc config top_padding         50
bspc config right_padding       0
bspc config bottom_padding      0
bspc config left_padding        0

bspc config split_ratio                       0.62
bspc config focus_follows_pointer             true
bspc config pointer_follows_monitor           true

bspc config focused_border_color "#7986cb"
bspc config active_border_color "#7986cb"
bspc config normal_border_color "#121315"
bspc config presel_feedback_color "#181818"

bspc monitor -d main web term av misc

bspc rule -a 'chromium' desktop=web
bspc rule -a 'WebTorrent' desktop=av
bspc rule -a 'Transmission-gtk' desktop=misc
bspc rule -a 'Nylas N1' desktop=misc

xsetroot -cursor_name left_ptr

~/.fehbg
bar.sh &
compton &
notify-osd &
