#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        1 
bspc config window_gap          20
bspc config top_padding         50
bspc config left_padding        15
bspc config right_padding       15
bspc config bottom_padding      15

bspc config split_ratio                       0.5
bspc config focus_follows_mouse               true
bspc config focus_by_distance                 false
bspc config borderless_monocle                true
bspc config gapless_monocle                   true

bspc config focused_border_color "#eeeeee"
bspc config active_border_color "#eeeeee"
bspc config normal_border_color "#212121"

feh --bg-fill /home/kabir/Pictures/buildingroof.jpg

compton &
/home/kabir/bin/wpanel &
